# Generated by Django 3.2.9 on 2021-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='total_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
