# Generated by Django 3.2.9 on 2022-03-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='parking_space',
            new_name='parking_spaces',
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
