# Generated by Django 3.2.9 on 2022-03-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220330_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='parkingLot',
            new_name='parking_lot',
        ),
        migrations.RenameField(
            model_name='lotoccupationhistory',
            old_name='parkingLot',
            new_name='parking_lot',
        ),
        migrations.RenameField(
            model_name='netmodel',
            old_name='parkingLot',
            new_name='parking_lot',
        ),
    ]
