# Generated by Django 3.2.9 on 2022-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220330_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodel',
            name='path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='trained_date',
            field=models.DateField(blank=True),
        ),
    ]
