# Generated by Django 3.2.9 on 2022-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220330_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodel',
            name='path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='trained_date',
            field=models.DateField(null=True),
        ),
    ]
