# Generated by Django 3.2.9 on 2022-03-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220330_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodel',
            name='type',
            field=models.CharField(choices=[('object_detection', 'object_detection'), ('clasification', 'clasification')], default='clasification', max_length=20),
            preserve_default=False,
        ),
    ]
