# Generated by Django 3.2.9 on 2022-03-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_netmodel_precision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netmodel',
            old_name='precision',
            new_name='accuracy',
        ),
    ]
