# Generated by Django 3.2.9 on 2022-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_precision_netmodel_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotoccupationhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
