# Generated by Django 3.2.9 on 2022-04-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_lotoccupationhistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceOccupancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('occupied', models.BooleanField()),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingspace')),
            ],
        ),
        migrations.RenameModel(
            old_name='LotOccupationHistory',
            new_name='LotOccupancyHistory',
        ),
        migrations.DeleteModel(
            name='SpaceOccupationHistory',
        ),
    ]
