# Generated by Django 3.2.9 on 2022-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220406_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodel',
            name='type',
            field=models.CharField(choices=[('object_detection', 'object_detection'), ('classification', 'classification')], max_length=20),
        ),
    ]
