# Generated by Django 3.2.9 on 2022-04-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_netmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceoccupancyhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
