# Generated by Django 3.2.9 on 2022-04-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_spaceoccupancyhistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netmodel',
            name='parking_lot',
        ),
    ]
