from .parkingLotSerializer import ParkingLotSerializer
from .cameraSerializer import CameraSerializer
from .boundingBoxSerializer import BoundingBoxSerializer
from .lotOccupationHistorySerializer import LotOccupationHistorySerializer
from .netModelSerializer import NetModelSerializer
from .parkingSpaceSerializer import ParkingSpaceSerializer
from .spaceOccupationHistorySerializer import SpaceOccupationHistorySerializer