from .parkingLotSerializer import ParkingLotSerializer
from .cameraSerializer import CameraSerializer
from .boundingBoxSerializer import BoundingBoxSerializer
from .lotOccupancyHistorySerializer import LotOccupancyHistorySerializer
from .netModelSerializer import NetModelSerializer
from .parkingSpaceSerializer import ParkingSpaceSerializer
from .spaceOccupancyHistorySerializer import SpaceOccupancyHistorySerializer
from .parkingLotOccupacySerializer import ParkingLotOccupacySerializer